version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/application.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: termix

build:
  run_buildscript: false

images:
  - id: termix
    target: service
    service: termix
    source: bugattiguy527/termix
    channel: stable
    tag_regex: '^v?[0-9]+\.[0-9]+\.[0-9]+$'
    delivery:
      mode: mirror
      image_template: docker.1ms.run/bugattiguy527/termix:{tag}
      require_digest_match: true

stores:
  official:
    enabled: false
    skip_if_version_exists: false
    retry:
      enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: Termix
    summary: "浏览器中的 SSH 终端与远程桌面客户端"
